services:
  postgres:
    image: postgres:${POSTGRES_VERSION} # Latest stable PostgreSQL version
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_HOST_PORT}:5432" # Expose the port for local connections
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data
    networks:
      - default

volumes:
  postgres_data: # This will create a Docker volume for persistent storage
    name: ${POSTGRES_VOLUME}

networks:
  default:
    name: ${NETWORK_NAME}
    driver: ${NETWORK_DRIVER}
